WORD_FREQ = 10
WINDOW_LENGTH = 5
VECTOR_LENGTH = 300
UPDATE_THRESHOLD = 100000
TOP_TRANS = 10
## DIR
CPR_DIR = "../vecmap/"
CNT_DIR = "./tempdata/count/"
VOCAB_DIR = ""
MATRIX_DIR = ""
RDM_VEC_DIR = ""
PAIRS_DIR = ""
RES_DIR = ""

